// Sri Sai Krishna Jewellers - Product Showcase Catalog
// Location: Etikoppaka | Phone / WhatsApp: +91 9573199344

const PRODUCTS_DATA = [
  {
    id: "ssk-gld-101",
    sku: "SSK-GLD-101",
    name: "22K Traditional Lakshmi Kasu Mala Long Haram",
    teluguName: "శ్రీ లక్ష్మీ కాసుల పేరు (లాంగ్ హారం)",
    category: "gold-bridal",
    metal: "gold",
    purity: "22K (916 BIS Hallmark)",
    approxGrossWeight: 48.5,
    approxNetWeight: 48.5,
    stoneDetails: "Kemp Rubies & Natural Emeralds",
    availability: "ready", // ready or custom
    availabilityText: "Available in shop",
    leadTime: "Instant Walk-in / Same Day Dispatch",
    badge: "Bestseller",
    image: "assets/kasu_mala.jpg",
    description: "Handcrafted masterwork featuring Lakshmi stamped gold coins (Kasu) interlinked with kemp stones, culminating in an opulent Nakshi Lakshmi peacock pendant with pearl drops.",
    featured: true
  },
  {
    id: "ssk-gld-102",
    sku: "SSK-GLD-102",
    name: "22K Antique Nakshi Peacock Bangles (Kadas) Pair",
    teluguName: "నక్షి మయూర బంగారు గాజులు (జత)",
    category: "gold-bridal",
    metal: "gold",
    purity: "22K (916 BIS Hallmark)",
    approxGrossWeight: 42.0,
    approxNetWeight: 39.5,
    stoneDetails: "Burmese Cut Rubies & Seed Pearls",
    availability: "ready",
    availabilityText: "Available in shop",
    leadTime: "Instant Walk-in / Express Delivery",
    badge: "916 Hallmarked",
    image: "assets/gold_bangles.jpg",
    description: "Royal South Indian Nakshi work bangles with dancing peacock motifs, handset with glowing rubies and side-screw closure for a comfortable, regal fit.",
    featured: true
  },
  {
    id: "ssk-gld-103",
    sku: "SSK-GLD-103",
    name: "22K Royal Guttapusalu Choker & Jhumka Bridal Set",
    teluguName: "రాయల్ గుత్తపూసల చోకర్ మరియు జుంకాల సెట్",
    category: "gold-bridal",
    metal: "gold",
    purity: "22K (916 BIS Hallmark)",
    approxGrossWeight: 56.2,
    approxNetWeight: 47.0,
    stoneDetails: "Basara Quality Rice Pearls, Rubies & Emerald",
    availability: "custom",
    availabilityText: "Made to order",
    leadTime: "7 - 10 Days Crafting Time",
    badge: "Artisan Handmade",
    image: "assets/hero.jpg",
    description: "Traditional coastal Andhra heritage Guttapusalu choker adorned with bunches of fine rice pearls, cabochon rubies, and emerald centerpiece with matching grand jhumkas.",
    featured: true
  },
  {
    id: "ssk-slv-201",
    sku: "SSK-SLV-201",
    name: "Pure 925 Silver Kamakshi Deepam & Kalasham Pooja Set",
    teluguName: "వెండి కామాక్షి దీపాలు & పూర్ణ కలశం పూజా సెట్",
    category: "silver-pooja",
    metal: "silver",
    purity: "Pure 925 Sterling Silver",
    approxGrossWeight: 320.0,
    approxNetWeight: 320.0,
    stoneDetails: "Plain Engraved Pure Silver",
    availability: "ready",
    availabilityText: "Available in shop",
    leadTime: "Instant Walk-in Available",
    badge: "Pooja Special",
    image: "assets/silver_pooja.jpg",
    description: "Sacred handcrafted pair of peacock Kamakshi oil lamps (diyas) accompanied by an embossed floral Kalasham and pooja spoon, ideal for Varalakshmi Vratham and housewarmings.",
    featured: true
  },
  {
    id: "ssk-gld-104",
    sku: "SSK-GLD-104",
    name: "22K Antique Heritage Temple Vaddanam (Waist Belt)",
    teluguName: "సంప్రదాయ దేవాలయ నక్షి వడ్డాణం",
    category: "gold-bridal",
    metal: "gold",
    purity: "22K (916 BIS Hallmark)",
    approxGrossWeight: 92.5,
    approxNetWeight: 88.0,
    stoneDetails: "Kemp Stones, Polki & Natural Pearls",
    availability: "custom",
    availabilityText: "Made to order",
    leadTime: "12 - 15 Days Custom Crafting",
    badge: "Heritage Masterpiece",
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80",
    description: "A show-stopping bridal Vaddanam sculpted with Ashtalakshmi figurines, flanked by peacocks and floral scrolls. Adjustable gold waist belt for an impeccable bridal silhouette.",
    featured: false
  },
  {
    id: "ssk-gld-105",
    sku: "SSK-GLD-105",
    name: "22K Antique Temple Peacock Buttalu / Jhumkas",
    teluguName: "నెమలి నక్షి బుట్టలు / జుంకాలు",
    category: "gold-daily",
    metal: "gold",
    purity: "22K (916 BIS Hallmark)",
    approxGrossWeight: 18.6,
    approxNetWeight: 17.2,
    stoneDetails: "Kemp Rubies & Gold Beaded Drops",
    availability: "ready",
    availabilityText: "Available in shop",
    leadTime: "Instant Walk-in Available",
    badge: "916 Hallmarked",
    image: "https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=800&q=80",
    description: "Classic South Indian umbrella jhumkas with filigree bell work, topped with an embossed peacock stud. Perfectly weighted for comfort during wedding celebrations.",
    featured: true
  },
  {
    id: "ssk-gld-106",
    sku: "SSK-GLD-106",
    name: "22K Traditional Nallapusalu (Black Beads) Mangalsutra Haram",
    teluguName: "సంప్రదాయ 22 క్యారెట్ నల్లపూసల గొలుసు",
    category: "gold-daily",
    metal: "gold",
    purity: "22K (916 BIS Hallmark)",
    approxGrossWeight: 16.5,
    approxNetWeight: 14.8,
    stoneDetails: "High-grade Black Spinel Beads & Rubies",
    availability: "ready",
    availabilityText: "Available in shop",
    leadTime: "Instant Walk-in / Customized Length in 2 Days",
    badge: "Auspicious",
    image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=80",
    description: "Double strand pure black beads chain handcrafted with 22K gold wire wrapping and an elegant floral Lakshmi pendant. Lightweight and durable for everyday wear.",
    featured: false
  },
  {
    id: "ssk-gld-107",
    sku: "SSK-GLD-107",
    name: "22K Men's Solid Royal Cuban / Rope Chain",
    teluguName: "పురుషుల దృఢమైన రాయల్ బంగారు గొలుసు",
    category: "gold-daily",
    metal: "gold",
    purity: "22K (916 BIS Hallmark)",
    approxGrossWeight: 28.4,
    approxNetWeight: 28.4,
    stoneDetails: "Solid 22K Gold (No Stones)",
    availability: "ready",
    availabilityText: "Available in shop",
    leadTime: "Instant Walk-in Available",
    badge: "Solid 916 Gold",
    image: "https://images.unsplash.com/photo-1598560917505-59a3ad559071?auto=format&fit=crop&w=800&q=80",
    description: "Durable, high-sheen 22K yellow gold men's chain with reinforced lobster clasp. Machine-cut precision interlinked with hand-finished polish.",
    featured: false
  },
  {
    id: "ssk-coin-301",
    sku: "SSK-COIN-301",
    name: "24K (999) Pure Gold Sri Lakshmi & Ganesha Coin (8g / 4g)",
    teluguName: "24 క్యారెట్ (999) శ్రీ లక్ష్మీ & వినాయక బంగారు కాయిన్",
    category: "gold-coins",
    metal: "gold",
    purity: "24K (999 Pure Gold)",
    approxGrossWeight: 8.0,
    approxNetWeight: 8.0,
    stoneDetails: "Tamper-proof Assay Certified Blister Pack",
    availability: "ready",
    availabilityText: "Available in shop",
    leadTime: "Instant Walk-in (Available in 1g, 2g, 4g, 8g)",
    badge: "999 Purity",
    image: "https://images.unsplash.com/photo-1610375461246-83df859d849d?auto=format&fit=crop&w=800&q=80",
    description: "Certified 999 fineness 24 Karat gold coin embossed with Goddess Lakshmi and Lord Ganesha. Perfect for Diwali, Akshaya Tritiya, and wedding gifting.",
    featured: false
  },
  {
    id: "ssk-slv-202",
    sku: "SSK-SLV-202",
    name: "925 Pure Silver Bridal Pattilu (Payal / Anklets)",
    teluguName: "స్వచ్ఛమైన వెండి వధువు పట్టీలు (గజ్జెలు)",
    category: "silver-jewellery",
    metal: "silver",
    purity: "925 Sterling Silver",
    approxGrossWeight: 78.0,
    approxNetWeight: 78.0,
    stoneDetails: "Silver Ghungroo Bells & Mina Work",
    availability: "ready",
    availabilityText: "Available in shop",
    leadTime: "Instant Walk-in Available",
    badge: "92.5 Certified",
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80",
    description: "Heavy traditional silver bridal anklets with resonant melodic chiming bells, antique oxidized detailing, and smooth interlocking links.",
    featured: true
  },
  {
    id: "ssk-slv-203",
    sku: "SSK-SLV-203",
    name: "Handcrafted Pure Silver Mayuri Kumkum Bharani & Plate",
    teluguName: "చేతితో చేసిన వెండి నెమలి కుంకుమ భరిణె",
    category: "silver-pooja",
    metal: "silver",
    purity: "Pure 925 Silver",
    approxGrossWeight: 45.0,
    approxNetWeight: 45.0,
    stoneDetails: "Peacock Engraved Pure Silver",
    availability: "ready",
    availabilityText: "Available in shop",
    leadTime: "Instant Walk-in Available",
    badge: "Traditional Gift",
    image: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80",
    description: "Auspicious pure silver peacock crest kumkum holder with an engraved matching base plate. Cherished wedding and festive gift.",
    featured: false
  },
  {
    id: "ssk-gld-108",
    sku: "SSK-GLD-108",
    name: "22K Custom Handcrafted Muvvala Haram (Mango Mala)",
    teluguName: "హ్యాండ్‌మేడ్ మామిడి పిందెల హారం (మావిడి కాయ మాల)",
    category: "gold-bridal",
    metal: "gold",
    purity: "22K (916 BIS Hallmark)",
    approxGrossWeight: 52.0,
    approxNetWeight: 49.0,
    stoneDetails: "Natural Kemp Stones & Gold Balls",
    availability: "custom",
    availabilityText: "Made to order",
    leadTime: "8 - 12 Days Custom Crafting",
    badge: "Custom Order",
    image: "https://images.unsplash.com/photo-1611591475152-4c83136ab5b6?auto=format&fit=crop&w=800&q=80",
    description: "Timeless South Indian Mango Mala featuring intricately stamped mango paisleys strung with kemp rubies and dangling golden muvvalu (bells). Made to order to your desired weight.",
    featured: false
  }
];

// Default Bullion Rates (Shop owner can update daily in UI or here)
const DEFAULT_RATES = {
  gold22k: 6850, // Rs per gram for 22K 916
  gold24k: 7475, // Rs per gram for 24K pure
  gold18k: 5605, // Rs per gram for 18K
  silver: 92     // Rs per gram for 92.5 Silver
};

// Store Information
const STORE_CONFIG = {
  name: "SRI SAI KRISHNA JEWELLERS",
  teluguName: "శ్రీ సాయి కృష్ణ జ్యువెలర్స్",
  tagline: "Heritage Craftsmanship & Timeless Purity",
  location: "Etikoppaka, Andhra Pradesh",
  phoneDisplay: "+91 9573199344",
  phoneRaw: "9573199344",
  whatsappNumber: "919573199344",
  timings: "9:00 AM - 9:00 PM (All Days Open)",
  address: "Sai Baba Gudi Center, Etikoppaka, Andhra Pradesh - 531082",
  mapsUrl: "https://maps.app.goo.gl/eypsoBYgweqtjr6c8",
  mapsLabel: "Venugopal Swami Temple, Etikoppaka"
};

export { PRODUCTS_DATA, DEFAULT_RATES, STORE_CONFIG };
